
# Display auto-configuration report when running a Spring Boot application
#debug: true

# Configure Spring specific properties
spring:
  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: auto

#  h2:
#    console:
#      enabled: true
#      path: /h2
#
#  # R2DBC Configuration
#  r2dbc:
#    url: r2dbc:h2:mem:///itemdb
#    username: root
#    password: root
#    initialization-mode: always


